### ISSUE TITLE
RELEASE.TXT file doesn't contain the "android equivalent version", foiling external tools

### ISSUE THREAD

**Issue by rpavlik** [crystax/android-platform-ndk#1]
We're using the [android-cmake "toolchain file"](https://github.com/taka-no-me/android-cmake) to build CMake-based software using the NDK. It parses `RELEASE.TXT` to extract the NDK version. However, since the CrystaX NDK contains custom wording  in that file, it can't parse it with the same basic logic as the upstream NDK, resulting in this error: https://github.com/OSVR/android-cmake/blob/master/android.toolchain.cmake#L429 https://gist.github.com/DuFF14/999730c5b4663939bc34

I imagine that part of this is a bug on the android-cmake side: it should be more resilient to the contents of `RELEASE.TXT`. However, it would be useful to the average user and possibly other scripts if the `RELEASE.TXT` file contained the value for the "equivalent" upstream release. I (as a human) looked at the change log HTML file which contains the version, but parsing a version out of there is a lot harder than out of the simple format in RELEASE.TXT

**Comment by rpavlik** [comment]
Ah, that makes sense. I'll raise an issue (and probably open a pull request) over with android-cmake then - didn't realize it was more subtle than a "this is r10d+improvements" relationship.  In that case, you might want to note something in the changelog file that the readme points to, then, since there it says the version is r10d.

**Comment by crystax** [comment]
You're right, changelog is wrong. I've added [ticket](https://tracker.crystax.net/issues/937) to fix it. Now, closing this issue.
