### ISSUE TITLE
python3.5 ssl problem

### ISSUE THREAD

**Issue by moyaying** [crystax/android-platform-ndk#19]
I use jni run python, but error...
Unexpected error: (<class 'ImportError'>, ImportError("No module named '_ssl'",), <traceback object at 0xee8c1da0>)

**Comment by vmurashev** [comment]
What build number of crystax-ndk do you use ?
There was no _ssl python module in officially released crystax-ndk-10.3.2
If you really want to try python and its SSL API, I recommend to take latest build from dl.crystax.net
In latest builds _ssl python module should work well

**Comment by moyaying** [comment]
thanks!   It work!
But other trouble, I cannot use third party packages when they containing C/C++ code.

**Comment by vmurashev** [comment]
Could you please be more specific then just saying "I cannot use third party packages" and specify what exactly doesn't work ? Is it a cross-compiling problem or something goes wrong at runtime and import of your module doesn't work ? Anyway you can mention the name of this module here, than it will be easier to talk about.
And the last if your module has nothing related to _ssl it would be better to submit a new bug

**Comment by moyaying** [comment]
Thank you for your answer, I will submit a new issue.
