### ISSUE TITLE
how to build third part python module write with c/c++

### ISSUE THREAD

**Issue by moyaying** [crystax/android-platform-ndk#21]
Hi, I run python with this library: https://github.com/joaoventura/pybridge
And I want to run https://github.com/scrapy/scrapy in Android, can I do that?

scrapy requirement some other module that write with c/c++, how to build them?

**Comment by vmurashev** [comment]
Well, I have several answers, please, choose one.
1. The most generic. You have to build your modules using the cross-compilers shipped with NDK whether by writing Android.mk or somehow different way.
2. If to paraphrase your question, I suppose it will be "How in general 3rd-party packages from PyPI - the Python Package Index  - can be integrated into Python  for Android shipped with NDK ?" And here there is no simple answer. Python setuptools don't support cross-compilation out of the box.
3. To overcome the situation I created a small repo https://github.com/vmurashev/crystax-pypi which has a tiny subset of packages from PyPI I found interesting for cryptography testing from python side. In this repo you can find several examples with Android.mk for binary python modules. This repo is ready to use almost out of the box. Say, if you are working in Linux and want populate your NDK with the package ```pyOpenSSL``` and its dependent packages, you can just type: ```$NDK/prebuilt/linux-x86_64/opt/python3.5/python setup.py pyOpenSSL --build --install```. Here $NDK is the directory where NDK is downloaded. As result you get the cross-compiled modules in ```$NDK/sources/python/3.5/shared/{abi}/site-packages/*```. Probably this repo is not the answer you looking for, but at least it should give you a hint.

**Comment by moyaying** [comment]
Sincere thanks, you get my point. Answer 3 is my needed.
