### ISSUE TITLE
cmake toolchain not included in normal crystax installer?

### ISSUE THREAD

**Issue by rcdailey** [crystax/android-platform-ndk#5]
I noticed that after extracting CrystaX NDK 10.3.1.1, the `cmake/toolchain.cmake` file is not present. Is this by design? Or is this CMake addition so new that it hasn't made it into the latest release?

**Comment by dmcrystax** [comment]
CMake support was added after 10.3.1 release date. If you want to play with CMake in CrystaX NDK, you should wait for the upcoming next release (11.0.0) or use latest daily build from https://dl.crystax.net/builds/.
