### ISSUE TITLE
error: only position independent executables (PIE) are supported.

### ISSUE THREAD

**Issue by MRebhan** [crystax/android-platform-ndk#7]
When trying to run the python binary for android (in the sources/python/3.5/libs folder) it gives that error message. It looks like those binaries are not built with the required -fPIE -pie arguments.

**Comment by dmcrystax** [comment]
https://tracker.crystax.net/issues/1486

**Comment by MRebhan** [comment]
Great! I'm waiting for it :D

**Comment by dmcrystax** [comment]
Fix is merged to master, and available since build [#900](https://dl.crystax.net/builds/900/)
